name: Continuous Delivery

on: [workflow_dispatch]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      deployments: write

    strategy:
      matrix:
        node-version: ["18"]

    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci .

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            WEB_PROD_URL
            CONTENTFUL_SPACE_ID
            CONTENTFUL_ACCESS_TOKEN
        env:
          WEB_PROD_URL: https://meguro.es
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
